package server

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"webtyp.com/router/routescan"
)

// GeneratedMainDir is the directory, relative to the project root, holding the
// generated server entry point. It must be inside the project: outside the
// module tree the Go toolchain cannot resolve the project's own imports.
const (
	GeneratedMainDir      = "web"
	GeneratedMainFilename = "server.go"

	// goModFilename is the module manifest read for the module path.
	goModFilename = "go.mod"
	// moduleDirectivePrefix is the token that opens the module line in go.mod.
	moduleDirectivePrefix = "module"
	// registerFuncName is the entry point every config/routes.go exports.
	registerFuncName = "Register"
	// routerArgExpr is the first argument passed to config.Register: the
	// running server's router.
	routerArgExpr = "s.Router()"
	// dependencyArg is what the generated call passes for every parameter
	// after the router.
	dependencyArg = "nil"

	dirPerm  os.FileMode = 0o755
	filePerm os.FileMode = 0o644
)

// MainConfig is what the generated main hardcodes.
type MainConfig struct {
	Port      string
	PublicDir string
	PlainHTTP bool
}

type mainTemplateData struct {
	ModulePath   string
	Port         string
	PublicDir    string
	PlainHTTP    bool
	RegisterArgs string
}

const runServerTemplateText = `//go:build !wasm

// Code generated by https://webtyp.com. DO NOT EDIT.
package main

import (
	"log"

	"{{.ModulePath}}/config"
)

func main() {
	if err := config.RunServer(); err != nil {
		log.Fatal(err)
	}
}
`

const mainTemplateText = `//go:build !wasm


// Code generated by https://webtyp.com. DO NOT EDIT.
package main

import (
	"log"
	"{{.ModulePath}}/config"
	"webtyp.com/server/httpd"
)

func main() {
	s := httpd.New(httpd.Config{
		Port:      "{{.Port}}",
		PublicDir: "{{.PublicDir}}",
		Gzip:      true,
		Health:    true,
		TLS:       httpd.TLSConfig{PlainHTTP: {{.PlainHTTP}}},
	})
	config.Register({{.RegisterArgs}})

	if err := s.ListenAndServe(); err != nil {
		log.Fatal(err)
	}
}
`

// HasRoutes reports whether the project declares routes and therefore needs a
// compiled server process.
func HasRoutes(rootDir string) bool {
	if hasRunServer(rootDir) {
		return true
	}
	routesFile := filepath.Join(rootDir, routescan.DefaultFile)
	_, err := os.Stat(routesFile)
	return err == nil
}

func hasRunServer(rootDir string) bool {
	configDir := filepath.Join(rootDir, "config")
	entries, err := os.ReadDir(configDir)
	if err != nil {
		return false
	}
	fset := token.NewFileSet()
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		node, err := parser.ParseFile(fset, filepath.Join(configDir, entry.Name()), nil, 0)
		if err != nil {
			continue
		}
		for _, decl := range node.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if ok && fn.Name.Name == "RunServer" {
				return true
			}
		}
	}
	return false
}

func readModulePath(rootDir string) string {
	content, err := os.ReadFile(filepath.Join(rootDir, goModFilename))
	if err != nil {
		return filepath.Base(rootDir)
	}
	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		fields := strings.Fields(strings.TrimSpace(line))
		if len(fields) >= 2 && fields[0] == moduleDirectivePrefix {
			return fields[1]
		}
	}
	return filepath.Base(rootDir)
}

// GenerateMain writes the server entry point for the project at rootDir and
// returns the absolute path of the written file.
//
// modulePath is the project's module path, read from go.mod.
func GenerateMain(rootDir, modulePath string, cfg MainConfig) (string, error) {
	outDir := filepath.Join(rootDir, GeneratedMainDir)
	if err := os.MkdirAll(outDir, dirPerm); err != nil {
		return "", fmt.Errorf("creating build directory: %w", err)
	}

	mainFile := filepath.Join(outDir, GeneratedMainFilename)
	absPath, err := filepath.Abs(mainFile)
	if err != nil {
		return "", fmt.Errorf("resolving absolute path: %w", err)
	}

	if content, readErr := os.ReadFile(absPath); readErr == nil {
		if !strings.Contains(string(content), "Code generated by https://webtyp.com") {
			return absPath, nil
		}
	}

	data := mainTemplateData{
		ModulePath: modulePath,
		Port:       cfg.Port,
		PublicDir:  cfg.PublicDir,
		PlainHTTP:  cfg.PlainHTTP,
	}

	tmplText := mainTemplateText
	if hasRunServer(rootDir) {
		tmplText = runServerTemplateText
	} else {
		routesFile := filepath.Join(rootDir, routescan.DefaultFile)
		data.RegisterArgs = detectRegisterArgs(routesFile)
	}

	tmpl, err := template.New("main").Parse(tmplText)
	if err != nil {
		return "", fmt.Errorf("parsing main template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing main template: %w", err)
	}

	if err := os.WriteFile(absPath, buf.Bytes(), filePerm); err != nil {
		return "", fmt.Errorf("writing generated main file: %w", err)
	}

	return absPath, nil
}

// detectRegisterArgs renders the argument list for the routes.Register call in
// the generated main. routescan reports the routes a project declares but not
// the signature of Register itself, so its arity is read here from the AST:
// the router is always the first argument, and every dependency parameter after
// it becomes a nil placeholder the developer fills in. Any parse failure falls
// back to the single-argument form rather than aborting generation.
func detectRegisterArgs(routesFile string) string {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, routesFile, nil, 0)
	if err != nil {
		return routerArgExpr
	}

	var targetFunc *ast.FuncDecl
	for _, decl := range node.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Type == nil || fn.Type.Params == nil {
			continue
		}
		if fn.Name.Name == registerFuncName {
			targetFunc = fn
			break
		}
		if targetFunc == nil && len(fn.Type.Params.List) > 0 {
			if isRouterParam(fn.Type.Params.List[0].Type) {
				targetFunc = fn
			}
		}
	}

	if targetFunc == nil {
		return routerArgExpr
	}

	paramCount := 0
	for _, field := range targetFunc.Type.Params.List {
		if len(field.Names) == 0 {
			paramCount++
		} else {
			paramCount += len(field.Names)
		}
	}

	if paramCount <= 1 {
		return routerArgExpr
	}

	args := make([]string, paramCount)
	args[0] = routerArgExpr
	for i := 1; i < paramCount; i++ {
		args[i] = dependencyArg
	}
	return strings.Join(args, ", ")
}

func isRouterParam(expr ast.Expr) bool {
	sel, ok := expr.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	ident, ok := sel.X.(*ast.Ident)
	if !ok {
		return false
	}
	return (ident.Name == "router" || ident.Name == "Router") && sel.Sel.Name == "Router"
}
